### ISSUE TITLE
support windows/arm64

### ISSUE THREAD

**Issue by gedw99** [cogentcore/webgpu#1]
This is in good shape and  works really well. 

Can we add windows arm64 also to:
https://github.com/cogentcore/webgpu/tree/main/wgpu/lib/windows ?

Its possible now but was not a few months ago: https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/

"These runners are available to our customers on our GitHub Team and Enterprise Cloud plans. We expect to begin offering Arm runners for open source projects by the end of the year."

You would need to go into your settings -> Actions -> runner groups -> then add an ARM runner :) This does mean for now, they are also not free in public repos.

```sh
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-arm-latest, windows-latest, macos-latest, macos-arm-latest]

    runs-on: ${{ matrix.os }}
```

You can test using UTM BTW if your on Mac, since its Arm also. But it can also emulate amd64 binaries.

https://github.com/utmapp/UTM

<img width="1728" alt="Screenshot 2024-08-13 at 20 30 25" src="https://github.com/user-attachments/assets/248b6c9a-b2e1-421d-86d6-3c034d5d1473">

**Comment by kkoreilly** [comment]
Thank you for the suggestion! We probably don't want to do this until they provide free runners for arm64. Also, do you know how much usage windows arm64 has in general? If there is not much usage and it can run amd64 binaries anyway, I'm not sure if we want to bloat the repository with more large object files. However, if there is decent usage, it is probably worth supporting this at some point. Also, thank you for linking to UTM; I didn't know about it!

**Comment by kkoreilly** [comment]
Thank you for all of the information! We will definitely consider supporting windows/arm64 once GitHub makes those runners free.

**Comment by johnnynunez** [comment]
January 2025

**Comment by kkoreilly** [comment]
There is no inherent issue to supporting `windows/arm64`, it is just that we do not have the `libwgpu_native.a` file because we automatically compile them using GitHub Workflows, for which we cannot use `windows/arm64`. If you can build or find the `libwgpu_native.a` file for `windows/arm64` for the correct version, we could upload it to add support for this. We are also planning to update to a new version of wgpu soon, so it may also make more sense to just wait until we do that and the free runners are available for this update; either way is fine.

**Comment by kkoreilly** [comment]
We implemented support for Windows and Linux arm64 in the commits above by compiling the `libwgpu_native.a` files in UTM on our macOS computers. Windows and Linux are fully functional in our experience on UTM after we fixed several key annoying bugs with WebGPU (see 0779a62c5a1b0835178b6a60d4df9b45477bd4ae and https://github.com/cogentcore/core/commit/b1423587c8a35eaf98a872681d62457a0e159fdc), with fast performance in 2D and full but somewhat slow functionality in 3D. We will add these new arm64 platforms to the CD once they are supported, but the current approach works fine for now.

You can test this with the latest version of Cogent Core on the main branch (https://github.com/cogentcore/core/pull/1341 is required). Thank you for recommending UTM, which was key for this and will allow us to debug many platform-specific issues much easier going forward!
